### ISSUE TITLE
Improve phpunit help docs

### ISSUE THREAD

**Issue by tarrow** [addshore/mwcli#7]
It would be awesome if the phpunit help docs had examples of how to run tests.

```
$ mw dev mediawiki phpunit --help
Runs MediaWiki phpunit in the MediaWiki container

Usage:
  mw docker mediawiki phpunit [flags]

Flags:
  -h, --help          help for phpunit
  -u, --user string   User to run as, defaults to current OS user uid:gid (default "1000:1000")

Global Flags:
  -v, --verbosity int   verbosity level (1-2) (default 1)
```

**Comment by addshore** [comment]
https://phabricator.wikimedia.org/T283407 [mwcli mwdd] Ensure users can pass phpunit related env vars to the phpunit commands
https://phabricator.wikimedia.org/T283408 [mwcli mwdd] Decide on the future of the phpunit command
https://phabricator.wikimedia.org/T282338 [mwcli mwdd] Ensure all key commands have examples in the help output

**Comment by addshore** [comment]
@tarrow Would you be able to go and create this as a ticket under https://phabricator.wikimedia.org/project/profile/5331/ ?

**Comment by tarrow** [comment]
moved to https://phabricator.wikimedia.org/T288364
