### ISSUE TITLE
Backup LocalSettings.php

### ISSUE THREAD

**Issue by tarrow** [addshore/mwcli#8]
At some point, perhaps during a `destroy` or `create` `mediawiki` command I totally lost my LocalSettings.php.

It would a) be good to produce a timestamped backup of this
and b) try to figure out what condition caused this in the first place

**Comment by addshore** [comment]
@tarrow Would you be able to go and create this as a ticket under https://phabricator.wikimedia.org/project/profile/5331/ ?

**Comment by tarrow** [comment]
moved to https://phabricator.wikimedia.org/T288365
